name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: onnxruntime=debug,onnxruntime-sys=debug
  RUST_BACKTRACE: 1

jobs:
  rustfmt:
    name: Run rustfmt
    runs-on: ubuntu-last
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  build:
    name: Build ors on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-apple-darwin,
            x86_64-pc-windows-msvc,
          ]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all
    - name: Cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-run
      
